in-cluster: false
spoof-nodes: false
spoof-kernels: false
spoof-specs: false
server-port: 8000
workload-presets-file: "configs/workload-presets-file.yaml"
gateway-address: gateway:8079
cluster-dashboard-handler-port: 8078
websocket-proxy-port: 8077
expected-origin-port: 8001
admin_username: "scusemua"
admin_password: "123456"

# How long JWT tokens are valid
token_valid_duration_sec: 3600

# How long users have to refresh their tokens
token_refresh_interval_sec: 5400